version: "3"
services:
  webhapi:
    image: cmstuning/hapitests:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - "3250:3100"
    networks:
      - webhapinet
  db:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - webhapinet     
networks:
  webhapinet: